import { type AssetRef, assetRefSchema } from "@/schemas/content/assetRef";

/**
 * Every image/video the site needs — CLAUDE.md §6.6. Photography and video
 * masters exist per the client (TODO(EMIN-Q43) video, TODO(EMIN-Q44) photos)
 * but have not been delivered to this build, so every entry ships as
 * `status: "placeholder"` with no `filename`. See docs/ASSET_MANIFEST.md for
 * the human-readable version of this same list.
 */
const raw: AssetRef[] = [
  {
    id: "home-hero-video",
    page: "home",
    subject: "Looping ambient exterior/garden footage for the hero background",
    kind: "video",
    width: 1920,
    height: 1080,
    priority: "normal",
    altText: "",
    decorative: true,
    status: "placeholder",
  },
  {
    id: "home-hero-poster",
    page: "home",
    subject: "Hero poster frame — the property's garden estate exterior",
    kind: "image",
    width: 1920,
    height: 1080,
    priority: "lcp",
    altText: "The Emin Pasha Hotel & Spa garden estate exterior, Nakasero, Kampala",
    status: "placeholder",
  },
  {
    id: "home-og-image",
    page: "home",
    subject: "Open Graph share image — garden estate exterior",
    kind: "image",
    width: 1200,
    height: 630,
    priority: "low",
    altText: "The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "room-superior-room",
    page: "accommodation/superior-room",
    subject: "Superior Room interior",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Superior Room at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "room-garden-room",
    page: "accommodation/garden-room",
    subject: "Garden Room interior opening onto the landscaped grounds",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Garden Room at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "room-garden-suites",
    page: "accommodation/garden-suites",
    subject: "Garden Suites interior",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Garden Suite at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "room-superior-suites",
    page: "accommodation/superior-suites",
    subject: "Superior Suites interior",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Superior Suite at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "dining-hakki-pasha",
    page: "dining/hakki-pasha-restaurant-bar",
    subject: "Hakki Pasha Restaurant & Bar dining room and bar",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Hakki Pasha Restaurant & Bar",
    status: "placeholder",
  },
  {
    id: "dining-sir-samuel-baker",
    page: "dining/sir-samuel-baker-fine-dining",
    subject: "Sir Samuel Baker Fine Dining room",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Sir Samuel Baker Fine Dining",
    status: "placeholder",
  },
  {
    id: "dining-rooftop-terrace",
    page: "dining/rooftop-terrace",
    subject: "The Rooftop Terrace with city views",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "The Rooftop Terrace at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "dining-manutea",
    page: "dining/manutea-wine-whisky-lounge",
    subject: "Manutea Wine & Whisky Lounge interior",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Manutea Wine & Whisky Lounge",
    status: "placeholder",
  },
  {
    id: "dining-in-room",
    page: "dining/in-room-dining",
    subject: "In-Room Dining service, Special-Select menu",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "In-room dining at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "lounge-acropole",
    page: "lounges/acropole-lounge",
    subject: "Acropole Lounge — fireplace, bar and alcove seating",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Acropole Lounge at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "lounge-mehmed-pasha",
    page: "lounges/mehmed-pasha-lounge",
    subject: "Mehmed Pasha Lounge with garden views",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Mehmed Pasha Lounge at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "lounge-equatorial-gardens",
    page: "lounges/equatorial-gardens",
    subject: "Equatorial Gardens — the outdoor event space",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "The Equatorial Gardens at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "spa-treatment-room",
    page: "spa",
    subject: "Swanky Spa treatment room / Turkish bath",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Swanky Spa & Wellness Centre",
    status: "placeholder",
  },
  {
    id: "spa-gym",
    page: "spa/gym",
    subject: "Emin Pasha Gym equipment floor",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Emin Pasha Gym",
    status: "placeholder",
  },
  {
    id: "spa-pool",
    page: "spa/pool",
    subject: "The swimming pool and poolside gardens",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Swimming pool at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "meetings-kudara-hall",
    page: "meetings-events/kudara-hall",
    subject: "Kudara Hall set up for a conference",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "Kudara Hall at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "meetings-private-rooms",
    page: "meetings-events/private-meeting-rooms",
    subject: "A private meeting room",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "Private meeting room at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "meetings-business-centre",
    page: "meetings-events/business-centre",
    subject: "The Business Centre workstation/meeting setup",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "The Business Centre at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "meetings-kudara-floorplan",
    page: "meetings-events/kudara-hall",
    subject: "Kudara Hall floor plan / capacity diagram",
    kind: "image",
    width: 1200,
    height: 1200,
    priority: "low",
    altText: "Kudara Hall floor plan and capacity diagram",
    status: "placeholder",
  },

  {
    id: "weddings-equatorial-gardens",
    page: "weddings",
    subject: "A wedding ceremony or reception set-up in the Equatorial Gardens",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "A wedding at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "experiences-airport-transfer",
    page: "experiences/airport-transfer",
    subject: "Airport transfer chauffeured vehicle",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "Airport transfer vehicle, The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },
  {
    id: "experiences-cg-shop",
    page: "experiences/cg-shop",
    subject: "Emin Pasha CG Shop interior and art pieces",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "The Emin Pasha CG Shop",
    status: "placeholder",
  },

  {
    id: "offers-friday-band-night",
    page: "offers",
    subject: "Friday Band Night — live music in the gardens after dark",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "Friday Band Night at The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "story-the-hotel",
    page: "our-story/the-hotel",
    subject: "The main building exterior, 2004 architecture reflecting Uganda's heritage",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "high",
    altText: "The Emin Pasha Hotel & Spa main building",
    status: "placeholder",
  },
  // TODO(EMIN-Q44): a historical portrait/engraving of Emin Pasha himself is
  // not confirmed as part of the delivered library, nor is its usage/rights
  // status — do not source one independently; wait for the client.
  {
    id: "story-emin-pasha-portrait",
    page: "our-story/emin-pasha",
    subject: "Historical portrait or engraving of Emin Pasha",
    kind: "image",
    width: 1200,
    height: 1500,
    priority: "high",
    altText: "Portrait of Emin Pasha",
    status: "placeholder",
  },
  // TODO(EMIN-Q21): GM name/photo not confirmed.
  {
    id: "story-gm-photo",
    page: "our-story/the-hotel",
    subject: "General Manager portrait",
    kind: "image",
    width: 800,
    height: 800,
    priority: "low",
    altText: "Portrait of the General Manager, The Emin Pasha Hotel & Spa",
    status: "placeholder",
  },

  {
    id: "gallery-exterior",
    page: "gallery",
    subject: "Garden estate exterior",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "The Emin Pasha Hotel & Spa exterior",
    status: "placeholder",
  },
  {
    id: "gallery-pool",
    page: "gallery",
    subject: "Pool and poolside gardens",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "Pool and poolside gardens",
    status: "placeholder",
  },
  {
    id: "gallery-gardens",
    page: "gallery",
    subject: "The Equatorial Gardens",
    kind: "image",
    width: 1600,
    height: 1067,
    priority: "normal",
    altText: "The Equatorial Gardens",
    status: "placeholder",
  },

  // TODO(EMIN-Q20): exact coordinates unresolved — static map cannot be
  // generated/commissioned against a pin until then.
  {
    id: "contact-static-map",
    page: "contact",
    subject: "Static map centred on Plot 27 Akii Bua Road, Nakasero",
    kind: "image",
    width: 1200,
    height: 800,
    priority: "normal",
    altText: "Map showing The Emin Pasha Hotel & Spa, Nakasero, Kampala",
    status: "placeholder",
  },
];

export const assets: AssetRef[] = raw.map((asset) => assetRefSchema.parse(asset));
